export const alimentosCategorizados = {
    verduras_legumes: [
        'Alface',
        'Rúcula',
        'Agrião',
        'Espinafre',
        'Tomate',
        'Cebola',
        'Pimentão',
        'Abóbora',
        'Cenoura',
        'Pepino',
        'Repolho',
        'Aipo',
        'Alho-poró'
    ],
    frutas: [
        'Maçã',
        'Banana',
        'Laranja',
        'Uva',
        'Morango',
        'Pera',
        'Melancia',
        'Abacaxi',
        'Melão',
        'Manga',
        'Pêssego'
    ],
    carnes_proteinas: [
        'Presunto',
        'Salame',
        'Peito de peru',
        'Presunto de frango',
        'Salsicha',
        'Peito de frango em fatias',
        'Salame de frango',
        'Salmão defumado',
        'Atum enlatado',
        'Sardinha enlatada'
    ],
    produtos_lacteos: [
        'Leite',
        'Iogurte',
        'Queijo',
        'Manteiga',
        'Creme de leite',
        'Leite condensado'
    ],
    produtos_secos_enlatados: [
        'Arroz',
        'Feijão',
        'Macarrão',
        'Farinha de trigo',
        'Farinha de milho',
        'Açúcar',
        'Sal',
        'Café',
        'Chá',
        'Óleo de cozinha',
        'Vinagre',
        'Molho de soja',
        'Molho de tomate',
        'Catchup',
        'Mostarda',
        'Maionese',
        'Azeitonas',
        'Conservas de vegetais',
        'Conservas de frutas',
        'Conservas de peixe',
        'Conservas de carne'
    ],
    outros: [
        'Pão',
        'Bolacha',
        'Torradas',
        'Cereal',
        'Granola',
        'Nozes',
        'Amêndoas',
        'Castanhas',
        'Frutas secas',
        'Barra de cereal',
        'Barras de cereais',
        'Barras de proteína',
        'Biscoitos',
        'Chocolate'
    ]
};

