export const alimentosCategorizados = {
    verduras_legumes: [
        'Alface',
        'Rúcula',
        'Agrião',
        'Espinafre',
        'Tomate',
        'Cebola',
        'Pimentão',
        'Abóbora',
        'Cenoura',
        'Pepino',
        'Repolho',
        'Aipo',
        'Alho-poró',
        'Couve',
        'Brócolis',
        'Couve-flor',
        'Batata',
        'Batata-doce',
        'Ervilha',
        'Vagem',
        'Berinjela',
        'Quiabo',
        'Chuchu',
        'Jiló'
    ],
    frutas: [
        'Maçã',
        'Banana',
        'Laranja',
        'Uva',
        'Morango',
        'Pera',
        'Melancia',
        'Abacaxi',
        'Melão',
        'Manga',
        'Pêssego',
        'Kiwi',
        'Limão',
        'Cereja',
        'Framboesa',
        'Amora',
        'Pitaya',
        'Goiaba',
        'Coco',
        'Ameixa',
        'Caqui'
    ],
    carnes_proteinas: [
        'Presunto',
        'Presunto de peru',
        'Presunto de frango',
        'Salame',
        'Salame de frango',
        'Salsicha',
        'Peito de frango em fatias',
        'Peito de frango',
        'Salame de frango',
        'Salmão defumado',
        'Atum enlatado',
        'Sardinha enlatada',
        'Carne bovina',
        'Carne suína',
        'Carne de frango',
        'Linguiça',
        'Bacon',
        'Costela',
        'Filé mignon',
        'Alcatra',
        'Picanha',
        'Frango assado',
        'Picadinha de alcatra',
    ],
    produtos_lacteos: [
        'Leite',
        'Leite integral',
        'Leite desnatado',
        'Leite sem lactose',
        'Iogurte',
        'Iogurte natural',
        'Iogurte de frutas',
        'Iogurte grego',
        'Iogurte sem lactose',
        'Queijo',
        'Queijo mussarela',
        'Queijo prato',
        'Queijo minas',
        'Queijo parmesão',
        'Manteiga',
        'Manteiga com sal',
        'Manteiga sem sal',
        'Creme de leite',
        'Creme de leite fresco',
        'Creme de leite de caixinha',
        'Leite condensado',
        'Leite condensado tradicional',
        'Leite condensado light',
        'Requeijão',
        'Requeijão cremoso',
        'Requeijão light',
        'Coalhada',
        'Coalhada fresca',
        'Coalhada seca',
        'Sorvete',
        'Sorvete de massa',
        'Sorvete de palito',
        'Sorvete de pote',
        'Sorvete de casquinha',
        'Sorvete de picolé',
        'Sorvete de cone',
        'Sorvete de copinho',
        'Sorvete de máquina',
        'Sorvete de chocolate',
        'Sorvete de baunilha',
        'Sorvete de morango',
    ],

    produtos_secos_enlatados: [
        'Arroz Branco 1kg',
        'Arroz Branco 5kg',
        'Arroz Integral 1kg',
        'Arroz Integral 5kg',
        'Arroz Agulhinha 1kg',
        'Arroz Agulhinha 5kg',
        'Arroz Parboilizado 1kg',
        'Arroz Parboilizado 5kg',
        'Arroz Arborio',
        'Feijão Branco 1kg',
        'Feijão Preto 1kg',
        'Macarrão Penne',
        'Macarrão Fetuccini',
        'Macarrão Espaguete',
        'Macarrão Parafuso',
        'Farinha de trigo',
        'Farinha de milho',
        'Açúcar',
        'Sal',
        'Café',
        'Café/Torrado/Moído',
        'Chá',
        'Óleo de cozinha',
        'Vinagre',
        'Molho de soja',
        'Molho de tomate',
        'Catchup',
        'Mostarda',
        'Maionese',
        'Azeitonas',
        'Conservas de vegetais',
        'Conservas de frutas',
        'Conservas de peixe',
        'Conservas de carne',
        'Milho enlatado',
        'Ervilha enlatada',
        'Sardinha em lata',
        'Atum em lata',
        'Feijão enlatado',
        'Tomate em lata',
        'Milho de pipoca',
        'Grão-de-bico'
    ],
    outros: [
        'Pão de forma branco', 'Pão de forma integral', 'Pão francês', 'Pão de centeio',
        'Bolacha Maria', 'Bolacha de maisena', 'Bolacha de chocolate', 'Bolacha recheada com creme de baunilha',
        'Torradas simples', 'Torradas integrais', 'Torradas com sementes', 'Torradas de alho',
        'Cereal de milho', 'Cereal de trigo', 'Cereal de aveia', 'Cereal de arroz',
        'Granola', 'Granola tradicional', 'Granola com frutas secas', 'Granola com castanhas', 'Granola com mel',
        'Nozes inteiras', 'Nozes picadas', 'Nozes caramelizadas', 'Nozes salgadas',
        'Amêndoas inteiras', 'Amêndoas fatiadas', 'Amêndoas torradas', 'Amêndoas caramelizadas',
        'Castanhas do Pará', 'Castanhas de caju', 'Castanhas portuguesas', 'Castanhas de baru',
        'Uvas passas', 'Damasco seco', 'Cranberries secas', 'Maçã desidratada',
        'Barra de cereal com aveia', 'Barra de cereal com frutas', 'Barra de cereal com chocolate', 'Barra de cereal light',
        'Barra de cereais de aveia', 'Barra de cereais de frutas', 'Barra de cereais de chocolate', 'Barra de cereais light',
        'Barra de proteína sabor chocolate', 'Barra de proteína sabor morango', 'Barra de proteína sabor baunilha', 'Barra de proteína sabor cookies',
        'Biscoito de maizena', 'Biscoito de chocolate', 'Biscoito de coco', 'Biscoito de aveia',
        'Chocolate ao leite', 'Chocolate meio amargo', 'Chocolate branco', 'Chocolate com castanhas',
        'Ovo de Páscoa ao leite', 'Ovo de Páscoa meio amargo', 'Ovo de Páscoa branco', 'Ovo de Páscoa recheado',
    ]
};

