export const alimentosCategorizados = {
    verduras_legumes: [
        'Alface',
        'Rúcula',
        'Agrião',
        'Espinafre',
        'Tomate',
        'Cebola',
        'Pimentão',
        'Abóbora',
        'Cenoura',
        'Pepino',
        'Repolho',
        'Aipo',
        'Alho-poró',
        'Couve',
        'Brócolis',
        'Couve-flor',
        'Batata',
        'Batata-doce',
        'Ervilha',
        'Vagem',
        'Berinjela',
        'Quiabo',
        'Chuchu',
        'Jiló'
    ],
    frutas: [
        'Maçã',
        'Banana',
        'Laranja',
        'Uva',
        'Morango',
        'Pera',
        'Melancia',
        'Abacaxi',
        'Melão',
        'Manga',
        'Pêssego',
        'Kiwi',
        'Limão',
        'Cereja',
        'Framboesa',
        'Amora',
        'Pitaya',
        'Goiaba',
        'Coco',
        'Ameixa',
        'Caqui'

    ],
    carnes_proteinas: [
        'Presunto',
        'Salame',
        'Peito de peru',
        'Presunto de frango',
        'Salsicha',
        'Peito de frango em fatias',
        'Salame de frango',
        'Salmão defumado',
        'Atum enlatado',
        'Sardinha enlatada',
        'Carne bovina',
        'Carne suína',
        'Carne de frango',
        'Linguiça',
        'Bacon',
        'Costela',
        'Filé mignon',
        'Alcatra',
        'Picanha',
        'Frango assado',
        'Peito de frango',
    ],
    produtos_lacteos: [
        'Leite',
        'Iogurte',
        'Queijo',
        'Manteiga',
        'Creme de leite',
        'Leite condensado',
        'Requeijão',
        'Coalhada',
        'Sorvete',
        'Sorvete de massa',
        'Sorvete de palito',
        'Sorvete de pote',
        'Sorvete de casquinha',
        'Sorvete de picolé',
        'Sorvete de cone',
        'Sorvete de copinho',
        'Sorvete de máquina',
        'Sorvete de chocolate',
        'Sorvete de baunilha',
        'Sorvete de morango',
    ],
    produtos_secos_enlatados: [
        'Arroz',
        'Feijão',
        'Macarrão',
        'Farinha de trigo',
        'Farinha de milho',
        'Açúcar',
        'Sal',
        'Café',
        'Café/Torrado/Moído',
        'Chá',
        'Óleo de cozinha',
        'Vinagre',
        'Molho de soja',
        'Molho de tomate',
        'Catchup',
        'Mostarda',
        'Maionese',
        'Azeitonas',
        'Conservas de vegetais',
        'Conservas de frutas',
        'Conservas de peixe',
        'Conservas de carne',
        'Milho enlatado',
        'Ervilha enlatada',
        'Sardinha em lata',
        'Atum em lata',
        'Feijão enlatado',
        'Tomate em lata',
        'Milho de pipoca',
        'Grão-de-bico'
    ],
    outros: [
        'Pão',
        'Bolacha',
        'Torradas',
        'Cereal',
        'Granola',
        'Nozes',
        'Amêndoas',
        'Castanhas',
        'Frutas secas',
        'Barra de cereal',
        'Barras de cereais',
        'Barras de proteína',
        'Biscoitos',
        'Chocolate',
        'Ovo de Páscoa',
    ]
};

