import { Stack, styled } from "@mui/system";
import { Root } from "../../styles/Root/root_styles";
import { Box, Typography } from "@mui/material";

export const StylesDetailsItems = {
    container: styled(Stack)(({ }) => ({
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: '1rem',
        width: "100%",
        minHeight: "99%",
        overflowX: 'hidden',
        overflowY: 'scroll',
        top: 0,
        left: 0,
        zIndex: 5,
        transition: 'all .3s',
        ...Root.scrollBar
    })),
    nav_bar: styled(Box)(() => ({
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        width: "100%",
        paddingBlock: '8px',
        height: "50px",
        borderBottom: `1px solid ${Root.color_button_opacity}`,
        boxSizing: 'border-box'
    })),
    container2: styled(Stack)(({ }) => ({
        position: 'relative',
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        gap: '1rem',
        width: '100%',
        minHeight: '300px',
        borderRadius: '8px',
        backgroundColor: Root.color_button_opacity,
        ...Root.boxShadow
    })),
    title: styled(Typography)(() => ({
        position: 'relative',
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        fontSize: '24px',
        fontWeight: 'bold',
        textAlign: 'center',
        fontFamily: Root.fontFamilyMonospace,
        ...Root.hover
    })),
    subtitle: styled(Typography)(({ minh }) => ({
        position: 'relative',
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        minHeight: minh && '35%',
        fontSize: '18px',
        fontWeight: 'bold',
        color: Root.color_button,
        textAlign: 'center',
        fontFamily: Root.fontFamilyMonospace,
        border: `${0.5}px solid ${Root.color_default}`,
        cursor: 'pointer',
        ...Root.hover
    })),
    sections: styled(Stack)(({ }) => ({
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: '12px',
        width: "95%",
        height: "90%",
        marginLeft: '16px'
    })),
    sectionsRow: styled(Stack)(({ }) => ({
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: '8px',
        textTransform: 'uppercase',
        color: Root.color_button,

    })),
    sectionsRowValue: styled(Stack)(({ }) => ({
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: Root.color_button,
        color: Root.color_default,
        padding: '10px',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontFamily: Root.fontFamilyMonospace,
    })),
    infeite: styled(Stack)(({ }) => ({
        position: 'absolute',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        top: 0,
        right: 0,
        borderTopLeftRadius: '50%',
        borderBottomRightRadius: '50%',
        backgroundColor: Root.color_button_opacity,
    })),
    image: styled(Stack)(({ }) => ({
        position: 'absolute',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        width: '40%',
        height: '100%',
        right: 0,
        top: 0,
    })),
    bar: styled(Stack)(({ }) => ({
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '4px',
        width: '100%',
        height: '60px',
        backgroundColor: Root.color_default,
        borderBottom: `1px solid ${Root.color_button_opacity}`,
        color: Root.color_button,
        fontWeight: 'bold',
        fontFamily: Root.fontFamilyMonospace,
    })),
    barTag: styled(Stack)(({ }) => ({
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '4px',
        width: '100%',
        height: '60px',
        borderRadius: '8px',
        fontFamily: Root.fontFamilyMonospace,
    })),

}